export const langObj = {
    ru: {
        headerTitle: 'Погода по всему миру',
        headerSearchPlaceholder: 'Поиск города',
        asOf: 'По состоянию на',
        feelsLike: 'Ощущается как',
        mmHg: 'мм рт.ст.',
        from: 'из',
        humidity: 'Влажность',
        pressure: 'Давление',
        currentConditionTitle: 'Погодные условия',
        wind: "Ветер",
        uv: 'Индекс УФ',
        dewPoint: 'Точка росы',
        cloudiness: 'Облачность',
        maxmin: 'Макс./Мин.',
        hourly: 'Почасовой прогноз',
        daily: 'Суточный прогноз',
        contact: 'Связаться со мной:',
        moon: {
            title: 'Фаза луны',
            newmoon: 'Новая луна',
            waxingcrescent: 'Растущий серп',
            firstquarter: 'Первая четверть',
            waxinggibbous: 'Растущая луна',
            fullmoon: 'Полная луна',
            waninggibbous: 'Убывающая луна',
            thirdquarter: 'Последняя четверть',
            waningcrescent: 'Старая луна',
        },
        todays: {
            title: "Прогноз на сегодня",
            morning: 'Утро',
            afternoon: 'День',
            evening: 'Вечер',
            night: 'Ночь',
        },
        buttons: {
            aqi: 'Подробнее',
            hourly: 'Прогноз на 48ч',
            daily: 'Прогноз на 7дн',
        },
        nav: {
            today: 'Сегодня',
            hourly: 'Почасовой прогноз',
            week: 'На 7 дней',
            airQuality: 'Индекс качества воздуха',
            maps: 'Карты'
        },
        menu: {
            lang: 'Язык',
            units: 'Система единиц',
            unitsMetric: 'Метрическая',
            unitsImperial: 'Имперская',
            themeTitle: 'Тема',
            themeLight: 'Светлая',
            themeDark: 'Темная'
        }
    },
    en: {
        headerTitle: 'Weather around the world',
        headerSearchPlaceholder: 'Search City',
        asOf: 'As of',
        feelsLike: 'Feels like',
        mmHg: 'mm Hg',
        from: 'from',
        humidity: 'Humidity',
        pressure: 'Pressure',
        currentConditionTitle: 'Weather Conditions',
        wind: 'Wind',
        uv: 'UV Index',
        dewPoint: 'Dew Point',
        cloudiness: 'Сloudiness',
        maxmin: 'Max/Min',
        hourly: 'Hourly Forecast',
        daily: 'Daily Forecast',
        contact: 'Contact me:',
        moon: {
            title: 'Moon phase',
            newmoon: 'New moon',
            waxingcrescent: 'Waxing Crescent',
            firstquarter: 'First Quarter',
            waxinggibbous: 'Waxing Gibbous',
            fullmoon: 'Full Moon',
            waninggibbous: 'Waning Gibbous',
            thirdquarter: 'Third Quarter',
            waningcrescent: 'Waning Crescent',
        },
        todays: {
            title: "Today's Forecast",
            morning: 'Morning',
            afternoon: 'Afternoon',
            evening: 'Evening',
            night: 'Night',
        },
        buttons: {
            aqi: 'more',
            hourly: 'Forecast for 48h',
            daily: 'Forecast for 7d',
        },
        nav: {
            today: 'Today',
            hourly: 'Hourly Forecast',
            week: 'For 7 days',
            airQuality: 'Air Quality Index',
            maps: 'Maps'
        },
        menu: {
            lang: 'Language',
            units: 'System of Units',
            unitsMetric: 'Metric',
            unitsImperial: 'Imperial',
            themeTitle: 'Theme',
            themeLight: 'Light',
            themeDark: 'Dark'
        }
    }
};